# Generated by Django 5.0.6 on 2025-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.IntegerField()),
                ('Employee_Name', models.CharField(max_length=30)),
                ('Employee_Email', models.EmailField(max_length=254)),
                ('Employee_Password', models.CharField(max_length=10)),
                ('Employee_Mobile', models.CharField(max_length=10)),
                ('Employee_Address', models.TextField()),
            ],
        ),
    ]
