# Generated by Django 5.0.6 on 2025-05-28 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_login',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 11, 7, 52, 625130, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
