# Generated by Django 5.0.6 on 2025-06-05 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_account', models.CharField(max_length=20)),
                ('To_account', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Remarks', models.TextField(blank=True)),
            ],
        ),
    ]
