# Generated by Django 5.0.6 on 2025-06-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Remarks',
            field=models.TextField(default=None),
        ),
    ]
