# Generated by Django 5.0.6 on 2025-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_transaction_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
