# Generated by Django 5.0.6 on 2025-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_AccountNo', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Customer_Phone', models.CharField(max_length=10)),
                ('Customer_Address', models.TextField()),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_FName', models.CharField(max_length=20)),
            ],
        ),
    ]
