# Generated by Django 5.0.6 on 2025-05-29 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='Customer_Password',
            field=models.CharField(default=datetime.datetime(2025, 5, 29, 13, 13, 48, 665674, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_AccountNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
