# Generated by Django 5.0.6 on 2025-05-29 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_remove_customer_id_customer_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Customer_Account_Type',
            field=models.CharField(default=datetime.datetime(2025, 5, 29, 13, 25, 30, 199572, tzinfo=datetime.timezone.utc), max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='Customer_Balance',
            field=models.DecimalField(decimal_places=2, default=122, max_digits=9),
            preserve_default=False,
        ),
    ]
