# Generated by Django 5.0.6 on 2025-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_customer_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_Balance',
            field=models.IntegerField(),
        ),
    ]
