# Generated by Django 5.0.6 on 2025-06-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Customer',
            fields=[
                ('Customer_AccountNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Customer_Phone', models.CharField(max_length=10)),
                ('Customer_Address', models.TextField()),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_FName', models.CharField(max_length=20)),
                ('Customer_Password', models.CharField(max_length=10)),
                ('Customer_Balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Customer_Account_Type', models.CharField(max_length=12)),
            ],
        ),
    ]
